services:

  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - ./requirements/wordpress/tools:/var/www/html
    expose:
      - "9000"
    networks:
      - inception-net

  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./requirements/wordpress/tools:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-net
    restart: always
    
networks:
  inception-net:
    driver: bridge