services:
  mariadb:
    build: ./requirements/mariadb
    # 例: image: mariadb:latest は禁止なので書かない
    # 代わりにDockerfileを自前で書き、そこで FROM debian:<version> などを指定
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    # restart: always なども指定

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network

volumes:
  mariadb_volume:
  wordpress_files:

networks:
  inception_network:
    driver: bridge
